### ISSUE TITLE
License and other small nits

### ISSUE THREAD

**Issue by dceejay** [coderofsalvation/node-red-contrib-splitter#1]
Hi,

a few quick comments if I may... 
- [ ] License is inconsistent... On NPM is says BSD - in README is says GPL - In files it says Apache. We like Apache-2.0 (or MIT) but up to you.
- [ ] You need to change the copyright in both js and html to be yours not IBM  (and 2014)
- [ ] html file - we normally put the name as the last item in the menu
- [ ] html file - we have moved to fa icons - so should now be "fa fa-tag" for the name label class
- [ ] html file - you are only passing back the property so no need for defaults for rules, checkall, or outputs
- [ ] html file - no need to have oneditprepare and oneditsave functions if not used.

**Comment by coderofsalvation** [comment]
Thanks for your feedback. I committed the following:

☑ changed to BSD ⟵ License is inconsistent... On NPM is says BSD - in README is says GPL - In files it says Apache. We like Apache-2.0 (or MIT) but up to you.

☑ done ⟵ You need to change the copyright in both js and html to be yours not IBM (and 2014)

☐ not sure what you mean by this:  we normally put the name as the last item in the menu

☑ introduced class="fa fa-ellipsis-h" on <label>-tag ⟵ we have moved to fa icons - so should now be "fa fa-tag" for the name label class

☑ removed ⟵ html file - you are only passing back the property so no need for defaults for rules, checkall, or outputs

☑ removed  ⟵ html file - no need to have oneditprepare and oneditsave functions if not used.

Any feedback or blessings appreciated.

**Comment by dceejay** [comment]
Great - thanks... Looks good !

No 3 -  - In the Edit panel  dialog we usually have the (optional) Name field as the last item of the menu list so it is in a consistent place. The only exceptions are the function and template nodes where they are actually used to save the function or templates in a library. All other nodes we have the name field at the bottom.
